---
- name: Install tmux
  hosts: all
  become: yes
  tasks:
    - name: Install Tmux
      package:
        name: tmux
        state: present

    - name: Verify tmux installation
      command: tmux -V
      register: tmux_version
      changed_when: false

    - name: Display tmux version
      debug:
        msg: "Tmux installed: {{ tmux_version.stdout }}"